name: CI/CD

on:
  push:
    branches:
      - staging
      - release
  pull_request:
  merge_group:

jobs:
  test:
    name: Typecheck and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run type check
        run: pnpm run typecheck

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
